# Exercise 1

# coin_flips = rbinom(500, 1, 0.3)
# range_n = 500
# generate_plot= function(sample, n, p){
#   plot(cumsum(sample), n, xlab="Xn", ylab="n", main="Plot of X against n", type="l")
#   lines(n*p, n, col="red")
# }
# 
# #generate_plot(coin_flips, 1:range_n, 0.3)
# 
# get_relative_error = function(sample, n, p){
#   vector_n = c(1:n)
#   error_vector = abs(cumsum(sample) - vector_n*p)/vector_n*p
#   plot(vector_n, error_vector, xlab="n", ylab="error", type="l")
# }

#get_relative_error(coin_flips, 500, 0.3)

# Exercise 3 - argument n = number or students chosen at random, expes = number of trials done

# Write a function that estimates P{A n } by simulating 100 experiments (that
# is, by taking 100 samples of size n) and finding out for each experiment (that
# is, for each sample) if A n occurs. Take n as the argument of the function.
# Hint: Use a for-loop.

birthday_experiments = function(n, expes){
  occurences = 0;
  for(i in 1:expes){
    sam = sample(1:365, n, replace=TRUE);
    event_An = FALSE;
    for(j in sam){
      if(length(which(sam == j)) >= 3){
        event_An = TRUE 
      }
    }
    if(event_An == T){
      occurences = occurences + 1
    }
  }
  return(occurences/expes);
}
#print(birthday_experiments(40, 100))
prob = numeric(200)
for(i in 1:200){
  prob[i] = birthday_experiments(i, 40)
}
#print(prob)
#plot(prob, 1:200)

estimate_n = function(n, expes){
  prob = numeric(n)
  least_n = 1
  for(i in 1:n){
    prob[i] = birthday_experiments(i, expes)
  }
  #prob[least_n] = birthday_experiments(least_n, expes)
  while(prob[least_n] < 0.7){
    least_n = least_n + 1
    #prob[least_n] = birthday_experiments(least_n, expes)
  }
  print(least_n)
}

#estimate_n(200,10000)

count_days = function(){
  vec_days = numeric(100);
  for(i in 1:100){
    sam = sample(1:365, 75, replace=TRUE);
    num_days = 0;
    for(day in sam){
      occurences = length(which(sam==day));
      if(occurences > 2){
        num_days = num_days + 1;
      }
    }
    vec_days[i] = num_days;
  }
  return(vec_days)
}

hist(count_days(), xlab="# days", main="Histogram of # days")

averages = numeric(100)
for(i in 1:100){
  averages[i] = mean(count_days())
}
#hist(averages, breaks=20)

# Exercise 4 
# Let X ∼ N (3, 16). Solve the following using the Normal table and using
# a computer package.
# (a) Find P(X < 7).
# (b) Find P(X > −2).
# (c) Find x such that P(X > x) = .05.
# (d) Find P(0 ≤ X < 4).
# (e) Find x such that P(|X| > |x|) = .05.

# (b) Simulate a random sample u of size n = 1.000 from the uniform distribution
# on (0, 1). Apply the quantile function F −1 to u element-wise and plot a
# scaled histogram of this transformed vector.
# Hint: A sample of size n from the uniform distribution on (a, b) can be
# generated by the R-command runif(n,a,b).
# (c) Compute the p.d.f. that corresponds to F and plot it on top of the histogram
# from (b).
# (d) Let a random variable U have uniform distribution on (0, 1). Prove that the
# c.d.f. of F −1 (U ) is F .
# Hint: The events {F −1 (U ) ≤ x} and {F (F −1 (U )) ≤ F (x)} are the same,
# why?
#   (e) Based on the previous parts of the exercise, how can you simulate a random
# variable with the c.d.f. F in R? Which of the previous parts of the exercise
# proves this approach works and which part illustrates this approach works?
#   (f) Which properties of F enable the approach from (e) to work? Would this
# approach work for other c.d.f.’s with these properties?


# R.4.b
# unif_sam = runif(1000, 0, 1)
# quantile_func = function(q){
#   return(log(q/(1-q)))
# }
# quantiled_sam = quantile_func(unif_sam)
# hist(quantiled_sam, xlab="quantile", freq=F, breaks=15, main="Histogram of quantile function")

#R.4.c
#pdf = function(x){
#   return(exp(x)/(1+exp(x))**2)
#}
#curve(dnorm(x, mean(quantiled_sam), sd(quantiled_sam)), add=T, lwd=1)
#?print(pdf(unif_sam))
#q_hist = hist(quantiled_sam, xlab="quantile", main="Histogram of quantile function")
#p_hist = hist(pdf(unif_sam), col="red")
#par(mfrow=c(q_hist,p_hist?))
#plot(q_hist, col=rgb(0,0,1,1/4))
#plot(p_hist, col="red", add=T)
#R.4.d

# Exercise R.2d
# draw_hist_curve = function(sam){
#   hist(sam, mean(sam), sd(sam), freq=F, breaks=10, xlab="value", main="Histogram of Sample");
#   curve(dnorm(x, 3, 4), add=T, lwd=1)
# }
# par(mfrow=c(3,3))
# draw_hist_curve(sample1)
# draw_hist_curve(sample2)
# draw_hist_curve(sample3)
# draw_hist_curve(sample4)
# draw_hist_curve(sample5)
# draw_hist_curve(sample6)